/*

 BG0.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : Z:\home\roocamp\Dropbox\GameDev\Exercises\BGScroll\bg0.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define background0Width 40
#define background0Height 18
#define background0Bank 0

extern unsigned char background0[];

/* End of BG0.H */
